/**
 * Todo el texto de la web vive aquí.
 * Para añadir inglés: duplicar como copy.en.ts, traducir los valores y cambiar
 * el import en src/content/index.ts. Ningún componente lleva texto propio.
 */
export const copy = {
  locale: "es-ES",
  meta: { brand: "VANTIS MOTORS", tagline: "Importación a la carta de vehículos de lujo" },
  nav: {
    links: [
      { id: "proceso", label: "Proceso" },
      { id: "disponibles", label: "Disponibles" },
      { id: "entregas", label: "Entregas" },
      { id: "coste", label: "Coste" },
      { id: "equipo", label: "Equipo" },
    ],
    cta: "Hacer un encargo",
    ctaShort: "Encargo",
    menuOpen: "Menú",
    menuClose: "Cerrar",
  },
  hero: {
    eyebrow: "Importación a la carta",
    headline: ["AQUÍ", "NO HAY", "STOCK."],
    headlineAccent: "HAY ENCARGOS.",
    body:
      "No hay stock. No hay catálogo. Describes el coche exacto que quieres: motor, acabado, color, kilometraje máximo. Lo localizamos en la Unión Europea y Estados Unidos, lo compramos, lo importamos, lo homologamos, lo matriculamos y te lo entregamos en tu puerta.",
    ctaPrimary: "Hacer un encargo",
    ctaSecondary: "Ver el proceso",
    scrollHint: "Desplaza",
    plateLabel: "Matrícula asignada",
    plateValue: "0000 VNT",
  },
  figures: {
    title: "Estado de operación",
    items: [
      { id: "mercados", value: 2, suffix: "", label: "Mercados de origen operativos", note: "Unión Europea y Estados Unidos." },
      { id: "plazo", value: 6, suffix: " sem", label: "Media desde encargo hasta entrega", note: "Medido sobre operaciones cerradas, no estimado." },
      { id: "operaciones", value: 84, suffix: "", label: "Operaciones cerradas", note: "Vehículos entregados y matriculados en España." },
      { id: "ahorro", value: 18, suffix: "%", label: "Ahorro medio frente a precio de concesionario nacional", note: "Comparado a configuración equivalente, impuestos incluidos." },
    ],
  },
  how: {
    eyebrow: "Cómo funciona",
    title: "Cinco pasos. Sin intermediarios ocultos.",
    steps: [
      { n: "01", title: "Encargo", body: "Nos das la configuración exacta: motor, transmisión, acabado, color, kilometraje máximo y año mínimo. Fijamos un techo de presupuesto por escrito.", data: "Plazo: 48 h para la primera búsqueda" },
      { n: "02", title: "Localización", body: "Rastreamos concesionarios oficiales, casas de subastas y stock privado en la UE y Estados Unidos. Te enviamos las unidades que cumplen, con VIN y ficha completa.", data: "UE y EE. UU. · VIN verificado" },
      { n: "03", title: "Inspección", body: "Inspección física independiente antes de transferir un euro. Informe de 120 puntos, peritaje de chapa y lectura de centralita.", data: "120 puntos de inspección" },
      { n: "04", title: "Importación", body: "Compra, transporte, despacho de aduanas y liquidación de impuestos. Recibes el desglose completo antes de firmar nada.", data: "Arancel 6,5% · IVA 21%" },
      { n: "05", title: "Entrega", body: "Homologación individual, ITV, impuesto de matriculación y placas. El coche llega a tu puerta listo para circular.", data: "Matriculado y entregado" },
    ],
  },
  showreel: {
    eyebrow: "Vitrina",
    title: "NO LO BUSCAS TÚ. LO BUSCAMOS NOSOTROS.",
    body: "Dos mercados rastreados a diario: concesionarios oficiales, casas de subastas y stock privado. Tú pones la configuración; nosotros ponemos las horas.",
    cta: "Hacer un encargo",
    ctaSecondary: "Ver unidades disponibles",
  },
  available: {
    eyebrow: "Disponible ahora",
    title: "Unidades localizadas.",
    body: "Unidades que hemos encontrado en nuestros mercados y siguen a la venta. El listado cambia a diario: confirma disponibilidad antes de tomar ninguna decisión.",
    labels: { year: "Año", km: "Kilometraje", market: "Mercado", price: "Puesto en España" },
    status: { available: "Disponible", reserved: "Reservado" },
    items: [
      { id: "D-118", model: "Volkswagen Golf GTI Clubsport", year: "2023", km: "14.200 km", market: "Alemania", price: "46.900 €", reserved: false, image: null },
      { id: "D-115", model: "Porsche 911 GT3 RS (992)", year: "2023", km: "6.800 km", market: "Alemania", price: "312.000 €", reserved: false, image: "/media/master.webp" },
      { id: "D-112", model: "BMW M3 Competition Touring", year: "2024", km: "9.400 km", market: "Alemania", price: "108.500 €", reserved: true, image: null },
      { id: "D-109", model: "BMW M3 E30 Evo II", year: "1988", km: "121.000 km", market: "Bélgica", price: "184.000 €", reserved: false, image: null },
      { id: "D-104", model: "Porsche 911 Carrera 3.2 Coupé", year: "1987", km: "96.500 km", market: "Estados Unidos", price: "89.400 €", reserved: false, image: null },
      { id: "D-101", model: "Audi RS6 Avant performance", year: "2023", km: "21.700 km", market: "Países Bajos", price: "126.900 €", reserved: false, image: null },
    ],
    cta: "Preguntar por una unidad",
    contact: "Contactar",
    photoPending: "Foto pendiente",
    note: "Precios orientativos con impuestos y gestión incluidos, calculados a fecha de publicación. No son una oferta en firme: cada unidad se cierra con presupuesto por escrito tras verificar disponibilidad y estado.",
  },
  team: {
    eyebrow: "Equipo",
    title: "Dos personas. Ningún intermediario.",
    body: "No hay centralita ni comerciales rotando. Hablas siempre con quien busca tu coche y con quien lo trae.",
    members: [
      { initials: "··", name: "Nombre Apellido", role: "Localización y compra", bio: "Pendiente de completar: dos o tres frases sobre trayectoria, mercados que cubre y por qué se le da bien encontrar unidades difíciles.", email: "nombre@vantismotors.com" },
      { initials: "··", name: "Nombre Apellido", role: "Importación y homologación", bio: "Pendiente de completar: dos o tres frases sobre trayectoria, aduanas, homologación individual y trato con la administración.", email: "nombre@vantismotors.com" },
    ],
  },
  deliveries: {
    eyebrow: "Entregas",
    title: "Operaciones cerradas",
    body: "Cada unidad se publica solo con permiso del cliente. Datos reales, sin retoque.",
    items: [
      { id: "VNT-0071", title: "Gran turismo V8", origin: "Stuttgart, Alemania", km: "18.400 km", weeks: "5 semanas", vin: "WXX·····ZZ71042" },
      { id: "VNT-0068", title: "Coupé biturbo", origin: "Milán, Italia", km: "9.120 km", weeks: "3 semanas", vin: "ZXX·····IT68115" },
      { id: "VNT-0064", title: "Roadster atmosférico", origin: "Miami, EE. UU.", km: "24.750 km", weeks: "8 semanas", vin: "1XX·····US64903" },
      { id: "VNT-0059", title: "Berlina deportiva", origin: "Róterdam, Países Bajos", km: "12.310 km", weeks: "3 semanas", vin: "XLX·····NL59277" },
      { id: "VNT-0055", title: "Coupé seis cilindros", origin: "Los Ángeles, EE. UU.", km: "31.980 km", weeks: "8 semanas", vin: "1XX·····US55461" },
      { id: "VNT-0052", title: "Gran turismo híbrido", origin: "Múnich, Alemania", km: "6.640 km", weeks: "5 semanas", vin: "WXX·····DE52338" },
    ],
    cardLabels: { origin: "Origen", km: "Kilometraje", weeks: "Plazo", vin: "VIN" },
  },
  markets: {
    eyebrow: "Mercados y rutas",
    title: "Dos orígenes. Un destino.",
    body: "Operamos donde el mercado premium de ocasión tiene volumen y trazabilidad. Cada origen tiene su plazo, su papeleo y su fiscalidad, y eso cambia el precio final.",
    destination: "España",
    diagramCaption: "Rutas operativas hacia España",
    labels: { transit: "Tránsito", duty: "Arancel", approval: "Homologación", sourcing: "Origen habitual" },
    routes: [
      {
        code: "UE",
        name: "Unión Europea",
        transit: "2–3 semanas",
        eu: true,
        note: "Operación intracomunitaria: el vehículo ya circula bajo normativa europea, así que entra sin arancel y sin homologación individual.",
        duty: "No aplica",
        approval: "No aplica",
        sourcing: "Alemania, Italia, Países Bajos y Bélgica",
      },
      {
        code: "US",
        name: "Estados Unidos",
        transit: "6–8 semanas",
        eu: false,
        note: "Flete marítimo y despacho de aduanas. El vehículo se homologa a título individual antes de poder matricularse en España.",
        duty: "Aplicable a la importación",
        approval: "Individual + ITV",
        sourcing: "Costa este, Florida y California",
      },
    ],
  },
  costs: {
    eyebrow: "Coste real",
    title: "Sin sorpresas.",
    body: "Esto es lo que compone el precio final. Lo recibes desglosado por escrito antes de que firmes nada.",
    toggle: { label: "Origen del vehículo", eu: "Origen UE", nonEu: "Origen EE. UU." },
    columns: { concept: "Concepto", rate: "Tipo" },
    rows: [
      { id: "arancel", concept: "Arancel aduanero", rate: "6,5% sobre el valor del vehículo", appliesEu: false },
      { id: "iva", concept: "IVA a la importación", rate: "21% sobre valor + arancel", appliesEu: true },
      { id: "iedmt", concept: "Impuesto de matriculación (IEDMT)", rate: "hasta 14,75% según emisiones", appliesEu: true },
      { id: "homologacion", concept: "Homologación individual e ITV", rate: "variable según origen", appliesEu: false },
      { id: "honorarios", concept: "Honorarios Vantis", rate: "acordados por escrito antes de empezar", appliesEu: true },
    ],
    notApplicable: "No aplica",
    legal: "Importes orientativos. Cada operación se cierra con presupuesto en firme por escrito, desglosado concepto a concepto, antes de iniciar la compra.",
  },
  form: {
    eyebrow: "Encargo",
    title: "Describe el coche.",
    body: "Cuatro campos. Respondemos en 48 horas con la primera búsqueda.",
    fields: {
      spec: { label: "Modelo y configuración deseada", placeholder: "Motor, transmisión, acabado, color, kilometraje máximo, año mínimo." },
      budget: { label: "Presupuesto orientativo", placeholder: "Techo aproximado, impuestos incluidos." },
      timing: { label: "Plazo", placeholder: "¿Para cuándo lo necesitas?" },
      contact: { label: "Cómo contactarte", placeholder: "Teléfono, email o WhatsApp." },
    },
    submit: "Enviar encargo",
    sending: "Enviando…",
    sent: "Encargo enviado",
    sentBody: "Recibido. Te escribimos en 48 horas con la primera búsqueda.",
    error: "No se ha podido enviar. Escríbenos por WhatsApp.",
    required: "Rellena este campo.",
    whatsapp: { label: "WhatsApp Business", action: "Abrir conversación", number: "+34 600 000 000", prefill: "Hola Vantis, quiero encargar un coche." },
    discretion: "Discreción por defecto. Los encargos no se publican sin permiso escrito del cliente.",
  },
  footer: {
    brand: "VANTIS MOTORS",
    tagline: "Importación a la carta de vehículos de lujo.",
    legalName: "Vantis Motors S.L.",
    vat: "B00000000",
    address: "Madrid, España",
    email: "encargos@vantismotors.com",
    rights: "Todos los derechos reservados.",
    links: [
      { label: "Aviso legal", href: "#" },
      { label: "Privacidad", href: "#" },
      { label: "Cookies", href: "#" },
    ],
    note: "Vantis Motors no es concesionario. No mantiene stock ni catálogo.",
  },
};
export default copy;
