/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiEstadoRouteImport } from './routes/api.estado'
import { Route as ApiSolicitudesRouteImport } from './routes/api.solicitudes'
import { Route as ApiSubirRouteImport } from './routes/api.subir'
import { Route as ApiUnidadesRouteImport } from './routes/api.unidades'
import { Route as InternoPublicarRouteImport } from './routes/interno.publicar'
import { Route as InternoSolicitudesRouteImport } from './routes/interno.solicitudes'
import { Route as UnidadesSlugRouteImport } from './routes/unidades.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEstadoRoute = ApiEstadoRouteImport.update({
  id: '/api/estado',
  path: '/api/estado',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolicitudesRoute = ApiSolicitudesRouteImport.update({
  id: '/api/solicitudes',
  path: '/api/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubirRoute = ApiSubirRouteImport.update({
  id: '/api/subir',
  path: '/api/subir',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnidadesRoute = ApiUnidadesRouteImport.update({
  id: '/api/unidades',
  path: '/api/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const InternoPublicarRoute = InternoPublicarRouteImport.update({
  id: '/interno/publicar',
  path: '/interno/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const InternoSolicitudesRoute = InternoSolicitudesRouteImport.update({
  id: '/interno/solicitudes',
  path: '/interno/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesSlugRoute = UnidadesSlugRouteImport.update({
  id: '/unidades/$slug',
  path: '/unidades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/estado': typeof ApiEstadoRoute
  '/api/solicitudes': typeof ApiSolicitudesRoute
  '/api/subir': typeof ApiSubirRoute
  '/api/unidades': typeof ApiUnidadesRoute
  '/interno/publicar': typeof InternoPublicarRoute
  '/interno/solicitudes': typeof InternoSolicitudesRoute
  '/unidades/$slug': typeof UnidadesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/estado': typeof ApiEstadoRoute
  '/api/solicitudes': typeof ApiSolicitudesRoute
  '/api/subir': typeof ApiSubirRoute
  '/api/unidades': typeof ApiUnidadesRoute
  '/interno/publicar': typeof InternoPublicarRoute
  '/interno/solicitudes': typeof InternoSolicitudesRoute
  '/unidades/$slug': typeof UnidadesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/estado': typeof ApiEstadoRoute
  '/api/solicitudes': typeof ApiSolicitudesRoute
  '/api/subir': typeof ApiSubirRoute
  '/api/unidades': typeof ApiUnidadesRoute
  '/interno/publicar': typeof InternoPublicarRoute
  '/interno/solicitudes': typeof InternoSolicitudesRoute
  '/unidades/$slug': typeof UnidadesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/estado'
    | '/api/solicitudes'
    | '/api/subir'
    | '/api/unidades'
    | '/interno/publicar'
    | '/interno/solicitudes'
    | '/unidades/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/estado'
    | '/api/solicitudes'
    | '/api/subir'
    | '/api/unidades'
    | '/interno/publicar'
    | '/interno/solicitudes'
    | '/unidades/$slug'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/estado'
    | '/api/solicitudes'
    | '/api/subir'
    | '/api/unidades'
    | '/interno/publicar'
    | '/interno/solicitudes'
    | '/unidades/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiEstadoRoute: typeof ApiEstadoRoute
  ApiSolicitudesRoute: typeof ApiSolicitudesRoute
  ApiSubirRoute: typeof ApiSubirRoute
  ApiUnidadesRoute: typeof ApiUnidadesRoute
  InternoPublicarRoute: typeof InternoPublicarRoute
  InternoSolicitudesRoute: typeof InternoSolicitudesRoute
  UnidadesSlugRoute: typeof UnidadesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/estado': {
      id: '/api/estado'
      path: '/api/estado'
      fullPath: '/api/estado'
      preLoaderRoute: typeof ApiEstadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/solicitudes': {
      id: '/api/solicitudes'
      path: '/api/solicitudes'
      fullPath: '/api/solicitudes'
      preLoaderRoute: typeof ApiSolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subir': {
      id: '/api/subir'
      path: '/api/subir'
      fullPath: '/api/subir'
      preLoaderRoute: typeof ApiSubirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unidades': {
      id: '/api/unidades'
      path: '/api/unidades'
      fullPath: '/api/unidades'
      preLoaderRoute: typeof ApiUnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interno/publicar': {
      id: '/interno/publicar'
      path: '/interno/publicar'
      fullPath: '/interno/publicar'
      preLoaderRoute: typeof InternoPublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interno/solicitudes': {
      id: '/interno/solicitudes'
      path: '/interno/solicitudes'
      fullPath: '/interno/solicitudes'
      preLoaderRoute: typeof InternoSolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades/$slug': {
      id: '/unidades/$slug'
      path: '/unidades/$slug'
      fullPath: '/unidades/$slug'
      preLoaderRoute: typeof UnidadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiEstadoRoute: ApiEstadoRoute,
  ApiSolicitudesRoute: ApiSolicitudesRoute,
  ApiSubirRoute: ApiSubirRoute,
  ApiUnidadesRoute: ApiUnidadesRoute,
  InternoPublicarRoute: InternoPublicarRoute,
  InternoSolicitudesRoute: InternoSolicitudesRoute,
  UnidadesSlugRoute: UnidadesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
